### PR TITLE
Handle some more CDP errors

### PR DESCRIPTION
**Pull request by celeryclub**
Hey team. Hope all is well.

I found a little issue with the multi-tab recording. On very fast machines, we may not have time to connect to a new tab and start recording before the tab is closed. This PR handles failures that sometimes happen when in this scenario.

Thank you!

### CODE REVIEW

**Comment by celeryclub** [comment]
@jperl Thank you for the merge! Do you think you'd have time to put out a patch release sometime soon?

**Comment by jperl** [comment]
Yes, sorry for the delay. Taking a long overdue vacation this week. Will release it first thing when we get back on Monday.

**Comment by celeryclub** [comment]
That's good. It's been a weird year for vacations. Glad you're making it happen!

**Comment by jperl** [comment]
@celeryclub Released in https://github.com/qawolf/playwright-video/releases/tag/v2.3.1 thanks for your patience 🙏

**Comment by celeryclub** [comment]
Thanks so much @jperl!

**Pull request merged**
