### PR TITLE
Increase FPS from 25 -> 60

### PR DESCRIPTION
**Pull request by andycloke**
I haven't done a huge amount with `ffmpeg`, but this seemed to increase the video quality for me.

If you'd prefer I could revert the default to 25 and add an optional config parameter where the user can set it to 60.

### CODE REVIEW

**Comment by jperl** [comment]
Thanks for your PR! Yes please make this an option and add it to the readme 🙏, since higher fps will increase the file size.

**Comment by donaldng** [comment]
Yes, this would be helpful!

**Comment by andycloke** [comment]
Updated

**Comment by jperl** [comment]
Thanks!

**Pull request merged**
