### PR TITLE
remove playwright-core

### PR DESCRIPTION
**Pull request by jperl**

### CODE REVIEW

**Comment by jperl** [comment]
This was just a test, based on a discussion from playwright slack. Where they were considering to remove playwright-core. This currently causes issues when you try to use this in a subpackage with typescript. Since it is expecting the types from the `playwright` package.

```
node_modules/playwright-video/build/PageVideoCapture.d.ts:1:22 - error TS2307: Cannot find module 'playwright' or its corresponding type declarations.
1 import { Page } from 'playwright';
                       ~~~~~~~~~~~~
node_modules/playwright-video/build/saveVideo.d.ts:1:22 - error TS2307: Cannot find module 'playwright' or its corresponding type declarations.
1 import { Page } from 'playwright';
                       ~~~~~~~~~~~~
.....

I am investigating if there is a way to bundle dependency types in the same package.

**Comment by celeryclub** [comment]
The jest-playwright team solved this problem like this: https://github.com/playwright-community/jest-playwright/blob/master/src/utils.ts#L15.

Not 100% sure that's the direction this project should take, but it's an idea.

**Comment by jperl** [comment]
That solves the issue of notifying the user they need the dependency. But I don't think it solves the typescript dependency issue.

**Comment by celeryclub** [comment]
I see... it was my assumption that this code could be used as a way to import types et al from any playwright-* package, but I may have been wrong.
https://github.com/playwright-community/jest-playwright/blob/master/src/utils.ts#L103

**Comment by jperl** [comment]
The issue arrises for me at build time when running `tsc` in a project consuming `playwright-video`, so I do not think that will fix it since it happens at run time.

**Comment by jperl** [comment]
Maybe using something like https://github.com/microsoft/TypeScript/issues/4433 would work (future supported in tsc https://github.com/microsoft/TypeScript/issues/4433).

**Pull request closed without merging**
